language: php
php:
  - 5.5
  - 5.4

before_script:
  - composer self-update
  - composer update --no-interaction

script:
 - mkdir -p build/logs
 - ./vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover=build/logs/clover.xml tests/

after_script:
 - php ./vendor/bin/coveralls -v

notifications:
  email:
    - dev@funivan.com