language: php
php:
  - 5.5
  - 5.4
  - 5.3
before_script:
    - composer dump-autoload

script: phpunit --coverage-text --configuration tests/phpunit.xml tests/

notifications:
  email:
    - dev@funivan.com